/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const VehicleType = IDL.Variant({
  'twoWheeler' : IDL.Null,
  'fourWheeler' : IDL.Null,
});
export const Time = IDL.Int;
export const Inquiry = IDL.Record({
  'id' : IDL.Nat,
  'vehicleType' : VehicleType,
  'name' : IDL.Text,
  'partRequired' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getInquiry' : IDL.Func([IDL.Nat], [Inquiry], ['query']),
  'submitInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, VehicleType, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const VehicleType = IDL.Variant({
    'twoWheeler' : IDL.Null,
    'fourWheeler' : IDL.Null,
  });
  const Time = IDL.Int;
  const Inquiry = IDL.Record({
    'id' : IDL.Nat,
    'vehicleType' : VehicleType,
    'name' : IDL.Text,
    'partRequired' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getInquiry' : IDL.Func([IDL.Nat], [Inquiry], ['query']),
    'submitInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, VehicleType, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };